title = "OWASP WebGoat Gitleaks Config"

[extend]
# Include the standard default Gitleaks rules
useDefault = true

[allowlist]
# Exclude historical or test secrets (if identified)
regexTarget = "match"
description = "Allowlist inactive or false-positive secrets"
regexes = [
  # Example placeholder patterns to ignore, customize as needed:
  '''deadbeef''',
  '''cafebabe'''
]

[filters]
# Skip build artifacts or docs not relevant to secret scanning
paths = [
  "docs/*",
  "config/*",
  "Dockerfile*",
  "*.md"
]

[[rules]]
description = "Detect server bind address (e.g., localhost)"
rule_name = "webgoat-localhost-port"
regex = '''127\.0\.0\.1'''
tags = ["webgoat", "bind-address"]

[[rules]]
description = "Detect inclusion of jar or binary artifacts"
rule_name = "embedded-jar"
regex = '''\.jar'''
tags = ["artifact"]

[[rules]]
description = "Detect AWS-style access keys"
rule_name = "aws-access-key"
regex = '''AKIA[0-9A-Z]{16,}'''
tags = ["credential", "aws"]

[[rules]]
description = "Detect secrets like password, API key keywords"
rule_name = "keyword-secret"
regex = '''(?i)(password|passwd|pwd|secret|apikey)[\s:=]+[^\s]+'''
tags = ["credential", "keyword"]

[[rules]]
description = "Detect potential RSA private keys"
rule_name = "private-key"
regex = '''-----BEGIN (RSA|DSA|EC|OPENSSH) PRIVATE KEY-----'''
tags = ["private_key"]