apiVersion: apps/v1
kind: Deployment
metadata:
  name: webgoat-practice-dep
  labels:
    app: webgoat-practice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webgoat-practice
  template:
    metadata:
      labels:
        app: webgoat-practice
    spec:
      containers:
        - name: webgoat-practice-container
          image: webgoat/webgoat:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 9090
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 8080
          #   initialDelaySeconds: 300
          #   periodSeconds: 60
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 8080
          #   initialDelaySeconds: 300
          #   periodSeconds: 60