name: 'Multi Security CI'

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  multi-sec:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    
    steps:
      - name: 'checkout code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      # secrets
      - name: 'Gitleaks'
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # Iac Scan
      - name: 'Checkov'
        uses: bridgecrewio/checkov-action@v12
        with:
          soft_fail: true
          quiet: true
          output_format: 'cli,sarif'
          output_file_path: 'checkov.sarif'
          framework: 'kubernetes'

      - name: 'Upload Checkov SARIF'
        uses: actions/upload-artifact@v4
        with:
          name: 'checkov-sarif'
          path: 'checkov.sarif'
          